[package]
name = "tcgdex_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.116"

[dependencies.reqwest]
version = "0.12"
features = ["json", "blocking"]

[dependencies.serde]
version = "1.0"
features = ["derive"]